version: "3.7"

x-common:
  &common-settings
  image: ${IMAGE}
  environment:
    - DATABASE_URL
    - NODE_ENV=production
    - RAILS_ENV=production
    - RAILS_LOG_TO_STDOUT="true"
    - RAILS_MASTER_KEY
    - RAILS_SERVE_STATIC_FILES="true"
    - VIRTUAL_HOST
    - RAILS_MAX_THREADS
    - DB_POOL
    - WEB_CONCURRENCY

services:
  web:
    << : *common-settings
    labels:
      - netguru.appname=quarantinehelper-backend
      - netguru.stage=production
    ports:
      - 80:3000
    logging:
      driver: awslogs
      options:
        awslogs-region: eu-central-1
        awslogs-group: loggroup-production
    command: bundle exec puma -C config/puma.rb
  sidekiq:
    <<: *common-settings
    command: bundle exec sidekiq
    hostname: quarantinehelper-backend.production.sidekiq
    restart: unless-stopped
  crono:
    <<: *common-settings
    command: bundle exec crono
    hostname: quarantinehelper-backend.production.crono
    restart: unless-stopped
