version: "3.7"

x-common:
  &common-settings
  build:
    context: ../../.
    dockerfile: docker/staging/Dockerfile.staging
  environment:
    - DATABASE_URL
    - NODE_ENV=production
    - RAILS_ENV=staging
    - RAILS_LOG_TO_STDOUT="true"
    - RAILS_MASTER_KEY
    - RAILS_SERVE_STATIC_FILES="true"
    - VIRTUAL_HOST

services:
  web:
    << : *common-settings
    labels:
      - netguru.appname=quarantinehelper-backend
      - netguru.stage=staging
    ports:
      - 80:3000
    command: bundle exec puma -C config/puma.rb
  redis:
    image: redis:5.0.9-alpine
    restart: unless-stopped
  sidekiq:
    << : *common-settings
    command: bundle exec sidekiq
    hostname: quarantinehelper-backend.staging.sidekiq
    restart: unless-stopped
  crono:
    <<: *common-settings
    command: bundle exec crono
    hostname: quarantinehelper-backend.staging.crono
    restart: unless-stopped